import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home () {
  return (
    <>
    <div style={{display:"flex",flexDirection:"row",justifyContent:"space-around"}}>
    
      <Link href="/about">
      <h3 >About</h3>
      </Link>

      <Link href='/Home'>
      <h3>Home</h3>
      </Link>
      
    </div>
    
      <Head>
        <title>Saif's-nextjs-first-project</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1>Welcome in next.js first project</h1>
        </div>
      </main>
    </>
  )
}
